# Dev: снижаем resource requests для экономии памяти
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-collector
  namespace: weather-pipeline
spec:
  template:
    spec:
      containers:
        - name: collector
          resources:
            requests:
              cpu: "50m"
              memory: "32Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"
